apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: npm-install
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: run-tests
      taskRef:
        name: run-jasmine-tests
      runAfter:
        - npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      taskRef:
        name: build-docker-image
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
