apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipelinerun
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: image-name
      value: "tax-calculator"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tax-calculator-pvc
