apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:18
      workingDir: $(workspaces.source.path)
      command:
        - npm
      args:
        - install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-jasmine-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: node:18
      workingDir: $(workspaces.source.path)
      command:
        - npm
      args:
        - test
